version: '3'
services:
  app:
    build:
      args:
        user: zairn
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravelsantafe
    container_name: laravelsantafe-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravelsantafe

  db:
    image: postgres:12.9
    container_name: laravelsantafe-db
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    networks:
      - laravelsantafe

  nginx:
    image: nginx:alpine
    container_name: laravelsantafe-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravelsantafe

networks:
  laravelsantafe:
    driver: bridge
